# Download
base-url: "https://www.tagesschau.de"

per-date-path: "/archiv/sendungsarchiv100~_date-DATE.html"
per-date-path-keyword: "DATE"
per-date-path-format: "%Y%m%d"
per-date-search-for-subpage: "tagesschau"

topics-text-discriminator: "Themen der Sendung"

date-format: "%Y.%m.%d"
start-date: 2021.01.01
end-date: 2021.01.22

# for some dates, we expect the web scraping to fail for various reasons.
# Hence we do not want to raise an error, when processing these dates
ignore-error-dates:
  - 2018.08.19 # no Tagesschau 20 Uhr exists for this date

target-path-prefix: "data/topics-"
target-path-suffix: ".txt"


# HTTP server
http-listen-port: 8080
find-path: "/find"
