version: "3.9"

services:
  # hot-reloading web-service
  tagesschau-web:
    container_name: tagesschau-web
    image: tagesschau-web:dev
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    command: npm run serve -- --port ${WEB_PORT}
    volumes:
      - ${PWD}/web/src:/web/src
    networks:
      - tagesschau-net
