version: "3.9"

services:

  tagesschau-runner:
    container_name: tagesschau-runner
    image: tagesschau:v1
    ports:
      - ${PORT}:${PORT}
    volumes:
      - tagesschau-data:/app/data
      - ./config:/app/config
    networks:
      - tagesschau-net

  # TODO: add webserver here.
  # TODO: add hot-reloading debug mode here: https://www.freecodecamp.org/news/how-to-enable-live-reload-on-docker-based-applications/

  tagesschau-reloader:
    container_name: tagesschau-reloader
    image: tagesschau-reloader:v1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tagesschau-data:/app/data
      - ./config:/app/config
    networks:
      - tagesschau-net

networks:
  tagesschau-net:
    name: tageschau-net

volumes:
  tagesschau-data:
    name: tagesschau-data
    driver: local-persist
    driver_opts:
      mountpoint: ${PWD}/data
