# Download
base-url: "https://www.tagesschau.de"

per-date-path: "/archiv/sendungsarchiv100~_date-DATE.html"
per-date-path-keyword: "DATE"
per-date-path-format: "%Y%m%d"
per-date-search-for-subpage: "tagesschau"

date-format: "%Y.%m.%d"
start-date: 2021.05.14
end-date: latest

# for some dates, we expect the web scraping to fail for various reasons.
# Hence we do not want to raise an error, when processing these dates
ignore-error-dates:
  - 2018.08.19 # no Tagesschau 20 Uhr exists for this date

# path is used for download as well as for later aggregation of data
data-folder: "data"
data-file-prefix: "topics-"
data-path-prefix: "data/topics-"
data-path-suffix: ".txt"


# HTTP server
http-listen-port: 11000
find-path: "/find"
text-path: "/text"
sum-path: "/sum"
http-date-format: "%Y.%m.%d"
